#include "MobileWalletAdapterSessionCommon.h"

BEGIN_IMPLEMENT_JAVA_CLASS_OBJECT(FMobileWalletAdapterSessionCommon, FJavaClassObjectEx,
	"com/solana/mobilewalletadapter/common/protocol/FMobileWalletAdapterSessionCommon",
	"(Lcom/solana/mobilewalletadapter/common/protocol/MessageReceiver;Lcom/solana/mobilewalletadapter/common/protocol/MobileWalletAdapterSessionCommon$StateCallbacks;)V")
END_IMPLEMENT_JAVA_CLASS_OBJECT